services:
  unified-platforms:
    build: .
    image: unified-platforms-gtm-os-unified-platforms:latest
    container_name: unified-platforms-app
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    labels:
      - traefik.enable=true
      - traefik.http.routers.my-unifiedplatforms.rule=Host(`my.unifiedplatforms.com`)
      - traefik.http.routers.my-unifiedplatforms.entrypoints=websecure
      - traefik.http.routers.my-unifiedplatforms.tls.certresolver=letsencrypt
      - traefik.http.services.my-unifiedplatforms.loadbalancer.server.port=3000
    networks:
      - traefik-lytx_default

networks:
  traefik-lytx_default:
    external: true
