import { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import { collection, query, where, getDocs, limit, doc, getDoc } from 'firebase/firestore';
import { db } from '../lib/firebase';
import SEO from '../components/SEO';
import { Loader2, CheckCircle2, Zap, Shield, Target, TrendingUp, Users, ArrowRight, Layout, Code, Server, Building, Globe, XCircle } from 'lucide-react';
import Navigation from '../components/layout/Navbar';

const IconPattern = ({ name, className }: { name: string, className?: string }) => {
  const icons: Record<string, any> = { Target, Zap, Shield, TrendingUp, Users, Layout, Code, Server, Building, Globe, CheckCircle2 };
  const Icon = icons[name] || CheckCircle2;
  return <Icon className={className || "w-6 h-6"} />;
};

export default function PSEOView() {
  const { slug } = useParams();
  const [page, setPage] = useState<any>(null);
  const [template, setTemplate] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchPSEOPage = async () => {
      if (!slug) return;
      try {
        const q = query(
          collection(db, 'pseo_pages'), 
          where('slug', '==', slug),
          where('status', '==', 'published'),
          limit(1)
        );
        const querySnapshot = await getDocs(q);
        if (!querySnapshot.empty) {
          const pageData = querySnapshot.docs[0].data();
          setPage(pageData);

          // Get template for meta tags
          if (pageData.templateId) {
            const templateSnap = await getDoc(doc(db, 'pseo_templates', pageData.templateId));
            if (templateSnap.exists()) {
              setTemplate(templateSnap.data());
            }
          }
        }
      } catch (err) {
        console.error(err);
      }
      setLoading(false);
    };
    fetchPSEOPage();
  }, [slug]);

  if (loading) {
    return (
      <div className="flex items-center justify-center h-screen bg-white">
        <Loader2 className="animate-spin text-cyan-600" size={32} />
      </div>
    );
  }

  if (!page || !template) {
    return (
      <div className="flex flex-col items-center justify-center h-screen bg-white">
        <h1 className="text-3xl font-bold text-gray-900 mb-4">404 - Page Not Found</h1>
        <p className="text-gray-500 mb-8">This location service page does not exist or has not been generated yet.</p>
        <Link to="/" className="text-cyan-600 font-semibold hover:underline flex items-center gap-2">
           Return Home <ArrowRight size={16}/>
        </Link>
      </div>
    );
  }

  const content = page.content;
  const isStructured = typeof content === 'object' && content !== null && content.hero;

  let metaTitle = template.h1Pattern?.replace('{city}', page.city || '') || `${page.city} Services`;
  let metaDesc = template.metaDescPattern?.replace('{city}', page.city || '').replace('{state}', page.state || '') || `Services in ${page.city}`;
  let schemaType = "Service";

  if (isStructured && content.seo) {
    metaTitle = content.seo.title || metaTitle;
    metaDesc = content.seo.meta_description || metaDesc;
    schemaType = content.seo.schema_type || schemaType;
  }

  return (
    <div className="bg-white min-h-screen text-gray-900 font-sans selection:bg-cyan-100 selection:text-cyan-900">
      <SEO title={metaTitle} description={metaDesc} />
      
      {/* Dynamic Content generated by Agent */}
      <main className="pt-24 pb-20">
        {!isStructured ? (
          /* Legacy String HTML Fallback */
          <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
            <div 
              className="prose prose-lg max-w-none prose-headings:text-gray-900 prose-a:text-cyan-600 hover:prose-a:text-cyan-700 prose-img:rounded-xl prose-img:shadow-lg"
              dangerouslySetInnerHTML={{ __html: content || '' }}
            />
          </div>
        ) : (
          /* Unified Architect Structured Layout */
          <article className="overflow-hidden">
            
            {/* HERO SECTION */}
            <section className="relative px-4 py-20 md:py-32 max-w-7xl mx-auto border-b border-gray-100">
              <div className="max-w-4xl">
                <div className="inline-flex items-center gap-2 px-3 py-1 bg-cyan-50 text-cyan-700 font-bold tracking-widest uppercase text-xs rounded-full mb-8">
                  <span className="w-2 h-2 rounded-full bg-cyan-500 animate-pulse" />
                  {page.city}, {page.state}
                </div>
                <h1 className="text-5xl md:text-7xl font-extrabold tracking-tight text-gray-900 leading-[1.1] mb-8">
                  {content.hero.h1}
                </h1>
                <p className="text-xl md:text-2xl text-gray-600 font-medium leading-relaxed max-w-3xl">
                  {content.hero.intro_text}
                </p>
                <div className="mt-10 flex gap-4">
                  <button className="bg-gray-900 text-white px-8 py-4 rounded-lg font-bold text-lg hover:bg-gray-800 transition-colors flex items-center gap-2">
                    Start Protocol <ArrowRight size={20} />
                  </button>
                </div>
              </div>
            </section>

            {/* VALUE GRID */}
            {content.value_grid && content.value_grid.length > 0 && (
              <section className="py-24 bg-gray-50 border-b border-gray-100">
                <div className="max-w-7xl mx-auto px-4">
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                    {content.value_grid.map((item: any, i: number) => (
                      <div key={i} className="bg-white p-8 rounded-2xl shadow-sm border border-gray-100 hover:shadow-md transition-shadow">
                        <div className="w-12 h-12 bg-cyan-50 rounded-xl flex items-center justify-center text-cyan-600 mb-6">
                           <IconPattern name={item.icon} />
                        </div>
                        <h3 className="text-xl font-bold text-gray-900 mb-3">{item.title}</h3>
                        <p className="text-gray-600 leading-relaxed">{item.description}</p>
                      </div>
                    ))}
                  </div>
                </div>
              </section>
            )}

            {/* MAIN FRAMEWORK / ENGINE */}
            {content.main_framework && (
              <section className="py-24 px-4 max-w-7xl mx-auto">
                <div className="max-w-2xl mb-16">
                  <h2 className="text-4xl font-extrabold text-gray-900">{content.main_framework.title}</h2>
                  <div className="h-1 w-20 bg-cyan-500 mt-6 rounded-full" />
                </div>
                
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
                  {content.main_framework.steps.map((step: any, idx: number) => (
                    <div key={idx} className="relative">
                      {idx < content.main_framework.steps.length - 1 && (
                        <div className="hidden lg:block absolute top-8 left-12 right-0 h-[2px] bg-gray-100 -z-10" />
                      )}
                      <div className="w-16 h-16 bg-gray-900 text-white rounded-2xl flex items-center justify-center font-bold text-2xl mb-6 shadow-xl">
                        {step.number}
                      </div>
                      <h4 className="text-lg font-bold text-gray-900 mb-2">{step.label}</h4>
                      <p className="text-gray-600 text-sm leading-relaxed">{step.detail}</p>
                    </div>
                  ))}
                </div>
              </section>
            )}

            {/* COMPARISON MODULE */}
            {content.comparison_module && (
              <section className="py-24 bg-gray-900 text-white">
                <div className="max-w-6xl mx-auto px-4">
                  <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 lg:gap-24">
                    {/* Left Side (Weak) */}
                    <div className="opacity-70">
                      <h3 className="text-2xl font-bold mb-8 flex items-center gap-3">
                        <XCircle className="text-red-400" />
                        {content.comparison_module.left_side_title}
                      </h3>
                      <ul className="space-y-4">
                        {content.comparison_module.left_side_points.map((pt: string, i: number) => (
                          <li key={i} className="flex gap-4 items-start">
                            <span className="w-1.5 h-1.5 bg-red-400 rounded-full mt-2.5 flex-shrink-0" />
                            <span className="text-gray-400 leading-relaxed">{pt}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                    
                    {/* Right Side (Architectural) */}
                    <div className="bg-gray-800 p-8 md:p-12 rounded-3xl border border-gray-700 shadow-2xl relative overflow-hidden">
                      <div className="absolute top-0 right-0 p-32 bg-cyan-500/10 blur-[100px] rounded-full pointer-events-none" />
                      <h3 className="text-2xl font-bold mb-8 flex items-center gap-3 text-white">
                        <CheckCircle2 className="text-cyan-400" />
                        {content.comparison_module.right_side_title}
                      </h3>
                      <ul className="space-y-6">
                        {content.comparison_module.right_side_points.map((pt: string, i: number) => (
                          <li key={i} className="flex gap-4 items-start">
                            <div className="w-6 h-6 rounded-full bg-cyan-500/20 text-cyan-400 flex items-center justify-center flex-shrink-0 mt-0.5">
                              <CheckCircle2 size={14} />
                            </div>
                            <span className="text-gray-200 leading-relaxed font-medium">{pt}</span>
                          </li>
                        ))}
                      </ul>
                      <div className="mt-12 pt-8 border-t border-gray-700">
                        <p className="text-cyan-400 font-bold uppercase tracking-wider text-sm flex items-center gap-2">
                           Deploy This Architecture <ArrowRight size={16} />
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </section>
            )}

            {/* GROWTH ENTITIES */}
            {content.growth_entities && content.growth_entities.length > 0 && (
              <section className="py-24 px-4 max-w-7xl mx-auto">
                <div className="text-center max-w-3xl mx-auto mb-16">
                  <h2 className="text-3xl font-bold text-gray-900 mb-4">Aligned Growth Entities</h2>
                  <p className="text-gray-600">Why this strategic infrastructure fits perfectly for these organizational types in {page.city}.</p>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  {content.growth_entities.map((entity: any, i: number) => (
                    <div key={i} className="bg-white border border-gray-100 p-8 rounded-2xl shadow-sm">
                      <h4 className="text-xl font-bold text-gray-900 mb-3">{entity.title}</h4>
                      <p className="text-gray-600 mb-6">{entity.description}</p>
                      <div className="bg-cyan-50 p-4 rounded-xl border border-cyan-100">
                        <p className="text-sm font-medium text-cyan-800">
                          <span className="font-bold text-cyan-900 mr-2">Context:</span>
                          {entity.context}
                        </p>
                      </div>
                    </div>
                  ))}
                </div>
              </section>
            )}

            {/* FAQ */}
            {content.faq && content.faq.length > 0 && (
              <section className="py-24 bg-gray-50 border-t border-gray-100">
                <div className="max-w-4xl mx-auto px-4">
                  <h2 className="text-3xl font-extrabold text-gray-900 mb-12 text-center">Technical FAQ</h2>
                  <div className="space-y-6">
                    {content.faq.map((faq: any, i: number) => (
                      <div key={i} className="bg-white border border-gray-100 p-6 md:p-8 rounded-2xl shadow-sm">
                        <h4 className="text-lg font-bold text-gray-900 mb-3 flex gap-4 items-start">
                          <span className="text-cyan-500 font-extrabold">Q.</span>
                          {faq.question}
                        </h4>
                        <p className="text-gray-600 leading-relaxed pl-8">
                           <span className="text-gray-400 font-bold mr-2">A.</span>
                           {faq.answer}
                        </p>
                      </div>
                    ))}
                  </div>
                </div>
              </section>
            )}

          </article>
        )}
      </main>
    </div>
  );
}
